/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    platformUsers: PlatformUserAuthOperations;
    externalUsers: ExternalUserAuthOperations;
  };
  blocks: {};
  collections: {
    platformUsers: PlatformUser;
    externalUsers: ExternalUser;
    invitations: Invitation;
    passwordResets: PasswordReset;
    channelPages: ChannelPage;
    contentPages: ContentPage;
    legalPages: LegalPage;
    media: Media;
    protectedFiles: ProtectedFile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    platformUsers: PlatformUsersSelect<false> | PlatformUsersSelect<true>;
    externalUsers: ExternalUsersSelect<false> | ExternalUsersSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    passwordResets: PasswordResetsSelect<false> | PasswordResetsSelect<true>;
    channelPages: ChannelPagesSelect<false> | ChannelPagesSelect<true>;
    contentPages: ContentPagesSelect<false> | ContentPagesSelect<true>;
    legalPages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    protectedFiles: ProtectedFilesSelect<false> | ProtectedFilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homePage: HomePage;
    navigation: Navigation;
    footerSettings: FooterSetting;
    loginSettings: LoginSetting;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footerSettings: FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    loginSettings: LoginSettingsSelect<false> | LoginSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: PlatformUser | ExternalUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PlatformUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ExternalUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platformUsers".
 */
export interface PlatformUser {
  id: number;
  displayName?: string | null;
  role: 'admin' | 'localAdmin' | 'internal';
  /**
   * Azure AD object ID — populated automatically on first SSO login.
   */
  azureId?: string | null;
  /**
   * Profile photo URL from Microsoft Graph — updated on each SSO login.
   */
  avatarUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'platformUsers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "externalUsers".
 */
export interface ExternalUser {
  id: number;
  /**
   * External users always have the external role.
   */
  role: 'external';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'externalUsers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  email: string;
  /**
   * SHA-256 hash of the raw invite token — never store the raw token.
   */
  tokenHash: string;
  expiresAt: string;
  used?: boolean | null;
  cancelled?: boolean | null;
  invitedBy: number | PlatformUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwordResets".
 */
export interface PasswordReset {
  id: number;
  user: number | ExternalUser;
  /**
   * SHA-256 hash of the raw reset token — never store the raw token.
   */
  tokenHash: string;
  expiresAt: string;
  used?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channelPages".
 */
export interface ChannelPage {
  id: number;
  title: string;
  /**
   * URL segment for this page (e.g. "brand-identity" for /brand-identity/).
   */
  slug: string;
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttons?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  cards?:
    | {
        title: string;
        excerpt?: string | null;
        image?: (number | null) | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentPages".
 */
export interface ContentPage {
  id: number;
  title: string;
  /**
   * URL segment for this page (e.g. "logo-usage" for /brand-identity/logo-usage/).
   */
  slug: string;
  excerpt?: string | null;
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            text: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            text: string;
            type: 'info' | 'warning';
            id?: string | null;
            blockName?: string | null;
            blockType: 'noteBlock';
          }
        | {
            rows: {
              cells: {
                content?: string | null;
                isHeader?: boolean | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tableBlock';
          }
        | {
            columns: '1' | '2' | '3' | '4' | '6';
            items: {
              image?: (number | null) | Media;
              title: string;
              url?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gridBlock';
          }
        | {
            title: string;
            image?: (number | null) | Media;
            link: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'collectionCardBlock';
          }
        | {
            label: string;
            file: number | ProtectedFile;
            id?: string | null;
            blockName?: string | null;
            blockType: 'downloadBlock';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'dividerBlock';
          }
        | {
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
      )[]
    | null;
  /**
   * Anchor navigation links shown in the anchor bar above the content.
   */
  anchors?:
    | {
        label: string;
        /**
         * The anchor ID to scroll to (without the # prefix).
         */
        anchor: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protectedFiles".
 */
export interface ProtectedFile {
  id: number;
  /**
   * Display name shown to users when downloading.
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages".
 */
export interface LegalPage {
  id: number;
  title: string;
  /**
   * URL segment for this page (e.g. "privacy-policy").
   */
  slug: string;
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            text: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            text: string;
            type: 'info' | 'warning';
            id?: string | null;
            blockName?: string | null;
            blockType: 'noteBlock';
          }
        | {
            rows: {
              cells: {
                content?: string | null;
                isHeader?: boolean | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tableBlock';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'dividerBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'platformUsers';
        value: number | PlatformUser;
      } | null)
    | ({
        relationTo: 'externalUsers';
        value: number | ExternalUser;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'passwordResets';
        value: number | PasswordReset;
      } | null)
    | ({
        relationTo: 'channelPages';
        value: number | ChannelPage;
      } | null)
    | ({
        relationTo: 'contentPages';
        value: number | ContentPage;
      } | null)
    | ({
        relationTo: 'legalPages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'protectedFiles';
        value: number | ProtectedFile;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'platformUsers';
        value: number | PlatformUser;
      }
    | {
        relationTo: 'externalUsers';
        value: number | ExternalUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'platformUsers';
        value: number | PlatformUser;
      }
    | {
        relationTo: 'externalUsers';
        value: number | ExternalUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platformUsers_select".
 */
export interface PlatformUsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  azureId?: T;
  avatarUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "externalUsers_select".
 */
export interface ExternalUsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  tokenHash?: T;
  expiresAt?: T;
  used?: T;
  cancelled?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwordResets_select".
 */
export interface PasswordResetsSelect<T extends boolean = true> {
  user?: T;
  tokenHash?: T;
  expiresAt?: T;
  used?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channelPages_select".
 */
export interface ChannelPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        title?: T;
        excerpt?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentPages_select".
 */
export interface ContentPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        noteBlock?:
          | T
          | {
              text?: T;
              type?: T;
              id?: T;
              blockName?: T;
            };
        tableBlock?:
          | T
          | {
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          content?: T;
                          isHeader?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gridBlock?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        collectionCardBlock?:
          | T
          | {
              title?: T;
              image?: T;
              link?: T;
              id?: T;
              blockName?: T;
            };
        downloadBlock?:
          | T
          | {
              label?: T;
              file?: T;
              id?: T;
              blockName?: T;
            };
        dividerBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  anchors?:
    | T
    | {
        label?: T;
        anchor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        noteBlock?:
          | T
          | {
              text?: T;
              type?: T;
              id?: T;
              blockName?: T;
            };
        tableBlock?:
          | T
          | {
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          content?: T;
                          isHeader?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dividerBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protectedFiles_select".
 */
export interface ProtectedFilesSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  heroImage: number | Media;
  heroHeadline: string;
  /**
   * Optional intro text shown below the headline (desktop only).
   */
  heroIntroText?: string | null;
  newInTitle: string;
  newInBody?: string | null;
  /**
   * "New in" section items. Recommended 4.
   */
  newInItems?:
    | {
        title: string;
        image: number | Media;
        link?: string | null;
        /**
         * Open link in a new tab.
         */
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  quickAccessTitle: string;
  quickAccessBody?: string | null;
  /**
   * Quick access shortcuts. Recommended 4.
   */
  quickAccessItems?:
    | {
        title: string;
        image: number | Media;
        link?: string | null;
        /**
         * Open link in a new tab.
         */
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Help/support buttons shown at the bottom of the homepage. Recommended 3.
   */
  helpButtons?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        /**
         * Show this button on the homepage.
         */
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Top-level navigation items (L1). Each can have L2 children, each L2 can have L3 children.
   */
  items?:
    | {
        label: string;
        page?:
          | ({
              relationTo: 'channelPages';
              value: number | ChannelPage;
            } | null)
          | ({
              relationTo: 'contentPages';
              value: number | ContentPage;
            } | null);
        /**
         * Show as a filter option in the homepage search bar.
         */
        showAsSearchFilter?: boolean | null;
        children?:
          | {
              label: string;
              page?:
                | ({
                    relationTo: 'channelPages';
                    value: number | ChannelPage;
                  } | null)
                | ({
                    relationTo: 'contentPages';
                    value: number | ContentPage;
                  } | null);
              /**
               * Show as a filter option in the homepage search bar.
               */
              showAsSearchFilter?: boolean | null;
              children?:
                | {
                    label: string;
                    page?: (number | null) | ContentPage;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings".
 */
export interface FooterSetting {
  id: number;
  brandName?: string | null;
  contactEmail?: string | null;
  copyright?: string | null;
  socialLinks?:
    | {
        icon: number | Media;
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        page?: (number | null) | LegalPage;
        /**
         * Use this for external links instead of a legal page.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loginSettings".
 */
export interface LoginSetting {
  id: number;
  image: number | Media;
  /**
   * Main heading shown above the login form.
   */
  title?: string | null;
  /**
   * Optional introductory paragraph shown below the title.
   */
  introduction?: string | null;
  /**
   * Optional secondary text shown below the introduction.
   */
  subtitle?: string | null;
  /**
   * Heading shown on the Change Password page.
   */
  changePasswordTitle?: string | null;
  /**
   * Optional introductory paragraph on the Change Password page.
   */
  changePasswordIntroduction?: string | null;
  /**
   * Label for the institutional link (e.g. "Visit ascendum.com").
   */
  institutionalLinkLabel?: string | null;
  /**
   * URL for the institutional link. Opens in a new tab.
   */
  institutionalLinkUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroImage?: T;
  heroHeadline?: T;
  heroIntroText?: T;
  newInTitle?: T;
  newInBody?: T;
  newInItems?:
    | T
    | {
        title?: T;
        image?: T;
        link?: T;
        newTab?: T;
        id?: T;
      };
  quickAccessTitle?: T;
  quickAccessBody?: T;
  quickAccessItems?:
    | T
    | {
        title?: T;
        image?: T;
        link?: T;
        newTab?: T;
        id?: T;
      };
  helpButtons?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        page?: T;
        showAsSearchFilter?: T;
        children?:
          | T
          | {
              label?: T;
              page?: T;
              showAsSearchFilter?: T;
              children?:
                | T
                | {
                    label?: T;
                    page?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  brandName?: T;
  contactEmail?: T;
  copyright?: T;
  socialLinks?:
    | T
    | {
        icon?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loginSettings_select".
 */
export interface LoginSettingsSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  introduction?: T;
  subtitle?: T;
  changePasswordTitle?: T;
  changePasswordIntroduction?: T;
  institutionalLinkLabel?: T;
  institutionalLinkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}